import BuildSystem

struct Build: ParsableCommand {
  static var configuration: CommandConfiguration {
    .init(subcommands: [
      PackageBuildCommand<Aribb24>.self,
      PackageBuildCommand<Ass>.self,
      PackageBuildCommand<BoringSSL>.self,
      PackageBuildCommand<CAres>.self,
      PackageBuildCommand<Ebml>.self,
      PackageBuildCommand<FdkAac>.self,
      PackageBuildCommand<Ffmpeg>.self,
      PackageBuildCommand<Ffms>.self,
      PackageBuildCommand<Flac>.self,
      PackageBuildCommand<Fmt>.self,
      PackageBuildCommand<Freetype>.self,
      PackageBuildCommand<Fribidi>.self,
      PackageBuildCommand<Gcrypt>.self,
      PackageBuildCommand<GpgError>.self,
      PackageBuildCommand<Harfbuzz>.self,
      PackageBuildCommand<Icu4c>.self,
      PackageBuildCommand<Jpcre2>.self,
      PackageBuildCommand<JpegXL>.self,
      PackageBuildCommand<Lame>.self,
      PackageBuildCommand<Lsmash>.self,
      PackageBuildCommand<Matroska>.self,
      PackageBuildCommand<Mediainfo>.self,
      PackageBuildCommand<Mkvtoolnix>.self,
      PackageBuildCommand<Mozjpeg>.self,
      PackageBuildCommand<Ninja>.self,
      PackageBuildCommand<Ogg>.self,
      PackageBuildCommand<Opencore>.self,
      PackageBuildCommand<Openssl>.self,
      PackageBuildCommand<Opus>.self,
      PackageBuildCommand<OpusTools>.self,
      PackageBuildCommand<Opusenc>.self,
      PackageBuildCommand<Opusfile>.self,
      PackageBuildCommand<Pcre2>.self,
      PackageBuildCommand<Png>.self,
      PackageBuildCommand<Pugixml>.self,
      PackageBuildCommand<Sdl2>.self,
      PackageBuildCommand<Vorbis>.self,
      PackageBuildCommand<Vpx>.self,
      PackageBuildCommand<Webp>.self,
      PackageBuildCommand<Xml2>.self,
      PackageBuildCommand<Xslt>.self,
      PackageBuildCommand<Xz>.self,
      PackageBuildCommand<Zstd>.self,
      PackageBuildCommand<Zvbi>.self,
      PackageBuildCommand<x264>.self,
      PackageBuildCommand<x265>.self,
    ])
  } // end of configuration
} // end of Build