#if !canImport(ObjectiveC)
import XCTest

extension BuilderSystemTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BuilderSystemTests = [
        ("testBuildEnvironment", testBuildEnvironment),
        ("testGetSDKPath", testGetSDKPath),
        ("testTriple", testTriple),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BuilderSystemTests.__allTests__BuilderSystemTests),
    ]
}
#endif
